/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tclxa_ndkdemo_JNIUtils */

#ifndef _Included_com_example_tclxa_ndkdemo_JNIUtils
#define _Included_com_example_tclxa_ndkdemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tclxa_ndkdemo_JNIUtils
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_tclxa_ndkdemo_JNIUtils_getStringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
